### ISSUE TITLE
Callback OutOfDomainServiceRequestCausesInquiryForAuthentication missing in OAS

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MultiDomainInventoryProxy#4]
The forwardingList contains the forwarding OutOfDomainServiceRequestCausesInquiryForAuthentication.
It is missing in the OAS and needs to be added.

See forwarding definition:
```
  - forwarding-name: OutOfDomainServiceRequestCausesInquiryForAuthentication
    uuid: mdip-1-0-0-op-fc-bm-004
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: /v1/inquire-oam-request-approvals
          uuid: mdip-1-0-0-op-s-bm-005
      fc-port-update:
        - server-name: /v1/inquire-oam-request-approvals
          uuid: mdip-1-0-0-op-s-bm-005
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/provide-list-of-connected-devices
        uuid: mdip-1-0-0-op-s-is-010
...
      - server-name: /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/wire-interface-2-0:wire-interface-pac/wire-interface-historical-performances
        uuid: mdip-1-0-0-op-s-is-274
    consequent-requests:
      - client-name: AdministratorAdministration://v1/approve-oam-request
        uuid: mdip-1-0-0-op-c-bs-aa-2-0-2-000
```
